CREATE DATABASE IF NOT EXISTS  ISTORIKH_EGKYKLOPAIDEIA;

USE ISTORIKH_EGKYKLOPAIDEIA;


CREATE TABLE IF NOT EXISTS BASEILIA(
BASILIA_ID VARCHAR(3) PRIMARY KEY ,
PROTEYOUSA CHAR(30) ,
GLWSSA_BAS CHAR(30),
HMEROMINIA_DIMIOURGIAS SMALLINT(4),
HMEROMINIA_KATASTROFHS SMALLINT(4)
)
;

CREATE TABLE IF NOT EXISTS E8NOS(
E8NOS_ID VARCHAR(3) PRIMARY KEY,
GLWSSA_E8 CHAR(30),
ONOMA_E8NOS CHAR(30),
HMEROMINIA_IDRISIS SMALLINT(4),
HMEROMINIA_KATASTROFIS SMALLINT(4)
);


CREATE TABLE IF NOT EXISTS PROSWPO(
	KWDIKOS CHAR(7) PRIMARY KEY, 
	ONOMA  CHAR(50),
    EPI8ETO CHAR(50),
    ETOS_GENISIS SMALLINT(4),
    ETOS_THANATOU SMALLINT(4),
    TOPOS_GENISIS VARCHAR(40),
    BASILIO_PR VARCHAR(3) NULL,
    E8NOS_PR VARCHAR(3) NULL,
    FOREIGN KEY (BASILIO_PR) REFERENCES BASEILIA(BASILIA_ID),
	FOREIGN KEY (E8NOS_PR) REFERENCES E8NOS(E8NOS_ID)
);


CREATE TABLE IF NOT EXISTS TOPO8ESIA(
MHKOS FLOAT,
PLATOS FLOAT,
PRIMARY KEY (MHKOS, PLATOS),
ONOMASIA VARCHAR(40),
HPEIROS CHAR(20)
);


 

CREATE TABLE IF NOT EXISTS GEGONOS(
KWDIKOS_G CHAR(5) PRIMARY KEY,
TITLOUS VARCHAR(60) NOT NULL,
ETOS SMALLINT(4),
DIKTIS_SIMANTIKOTITAS  INT NOT NULL CHECK(DIKTIS_SIMANTIKOTITAS BETWEEN 1 AND 9),
DIKTIS_EPIRROHS INT NOT NULL CHECK(DIKTIS_EPIRROHS BETWEEN 1 AND 10)
);
 /**/
CREATE TABLE IF NOT EXISTS TITLOS(
KWDIKOS_T VARCHAR (4) PRIMARY KEY,
KATHGORIA_TITLOY CHAR(30),
ETOS_BRABE SMALLINT(4),
ONOMA_BRABEIOU CHAR(50)
);
 /**/
CREATE TABLE IF NOT EXISTS PHGES(
KWDIKOS_P VARCHAR(4) PRIMARY KEY,
ONOMA_SIG CHAR(30),
EPI8ETO_SIG CHAR(30),
ETOS_EKDOSIS_P SMALLINT(4)
);

CREATE TABLE IF NOT EXISTS SXOLIKA_BIBLIA(
KWDIKOS_BIBLIA VARCHAR(3) PRIMARY KEY,
ONOMA_BIBLIOY CHAR(50),
MA8HMA CHAR(40),
KEFALAIO VARCHAR(10),
BA8MIDA_EKPEDEYSHS CHAR(30)
);




CREATE TABLE IF NOT EXISTS GEGONOS_TOPO8ESIA(
MHKOS_GT FLOAT,
PLATOS_GT FLOAT,
KWDIKOS_GT CHAR(5) ,
PRIMARY KEY (MHKOS_GT,PLATOS_GT,KWDIKOS_GT),
FOREIGN KEY (MHKOS_GT ,PLATOS_GT) REFERENCES TOPO8ESIA(MHKOS,PLATOS),
FOREIGN KEY (KWDIKOS_GT) REFERENCES GEGONOS(KWDIKOS_G)
);



CREATE TABLE IF NOT EXISTS SXOLIKA_BIBLIA_PROSWPO(
KWDIKOS_BIBLIOY_S CHAR(40),
KWDIKOS_PROSWPO_S CHAR(7),
PRIMARY KEY (KWDIKOS_BIBLIOY_S,KWDIKOS_PROSWPO_S),
FOREIGN KEY (KWDIKOS_BIBLIOY_S) REFERENCES SXOLIKA_BIBLIA(KWDIKOS_BIBLIA),
FOREIGN KEY (KWDIKOS_PROSWPO_S) REFERENCES PROSWPO(KWDIKOS)
);


 /**/
CREATE TABLE IF NOT EXISTS  GEGONOS_PHGES(
KWDIKOS_PHGHS VARCHAR(4),
KWDIKOS_GEGONOS_P CHAR (5),
PRIMARY KEY (KWDIKOS_PHGHS,KWDIKOS_GEGONOS_P),
FOREIGN KEY (KWDIKOS_PHGHS) REFERENCES PHGES(KWDIKOS_P),
FOREIGN KEY (KWDIKOS_GEGONOS_P) REFERENCES GEGONOS(KWDIKOS_G)
);


 /**/
CREATE TABLE IF NOT EXISTS PROSWPO_TITLOS(
KWDIKOS_TITLOS VARCHAR(4),
KWDIKOS_PROSWPO_T CHAR(7),
PRIMARY KEY(KWDIKOS_TITLOS,KWDIKOS_PROSWPO_T),
FOREIGN KEY (KWDIKOS_TITLOS) REFERENCES TITLOS(KWDIKOS_T),
FOREIGN KEY (KWDIKOS_PROSWPO_T) REFERENCES PROSWPO(KWDIKOS)
);


CREATE TABLE IF NOT EXISTS PROSWPO_GEGONOS(
KWDIKOS_PROSWPO CHAR(7),
KWDIKOS_GEGONOS CHAR(5),
PRIMARY KEY (KWDIKOS_PROSWPO,KWDIKOS_GEGONOS),
FOREIGN KEY (KWDIKOS_PROSWPO) REFERENCES PROSWPO(KWDIKOS),
FOREIGN KEY (KWDIKOS_GEGONOS) REFERENCES GEGONOS(KWDIKOS_G)
);













 
 /*DROP TABLES*/
DROP TABLE GEGONOS_TOPO8ESIA;
DROP TABLE SXOLIKA_BIBLIA_PROSWPO;
DROP TABLE GEGONOS_PHGES;
DROP TABLE PROSWPO_TITLOS;
DROP TABLE PROSWPO_GEGONOS;
DROP TABLE GEGONOS;
DROP TABLE TOPO8ESIA;
DROP TABLE PROSWPO;
DROP TABLE BASEILIA;
DROP TABLE E8NOS;
DROP TABLE SXOLIKA_BIBLIA;
DROP TABLE PHGES;
DROP TABLE TITLOS;


